version: '2'
services:
    umsaccount-app:
        image: umsaccount
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://umsaccount-mysql:3306/umsaccount?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://umsaccount-elasticsearch:9200
        ports:
            - 8080:8080
    umsaccount-mysql:
        extends:
            file: mysql.yml
            service: umsaccount-mysql
    umsaccount-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: umsaccount-elasticsearch
